version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jwt-frontend
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://10.5.1.59:8080
    restart: always

#docker compose down; docker compose build; docker compose up -d